name: Produce Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
    - name: Make Step 1
    - continue-on-error: true
      run: make
    - name: Make Step 2
      run: make
      
